config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'games#index'
  get 'team', to: 'static_pages#team'
  resources :games do
    collection do
      get :pending
      get :playing
      get :complete
    end
    member do
      post :forfeit
      post :castle_king_side
      post :castle_queen_side
    end

  end
  resources :pieces
end

app/models/game.rb
class Game < ApplicationRecord


  ## Results of the game after the game is over enumerated within the result column
  enum result: {black_wins: 0, white_wins: 1, stalemate: 2}

  has_many	:pieces

  belongs_to :white_player, :class_name => 'User', :foreign_key => 'white_player_id'
  belongs_to :black_player, :class_name => 'User', :foreign_key => 'black_player_id', optional: true

  scope :pending,  ->{ where(black_player_id: nil)}
  scope :playing,  ->{ where.not(black_player_id: nil).where(result: nil)}
  scope :complete, ->{ where(winner_id: true).where.not(result: nil)}

  after_create :populate_game!

  def forfeit!(player)
    if player == white_player
      update!(:result => 0, :winner_id => black_player_id)
    elsif player == black_player
      update!(:result => 1, :winner_id => white_player_id)
    end
  end

  def name(player)
    if player == self.white_player_id
        User.find(self.black_player_id).email
    else
        User.find(self.white_player_id).email
    end
    
  end

  def next_player(player)
    if player == self.white_player_id
      self.update_attributes(next_player_id: self.black_player_id)
      self.reload
    else
      self.update_attributes(next_player_id: self.white_player_id)
       self.reload
    end
  end

  def opponent_players(player)
    players = []
    if player == self.white_player_id
      players << self.black_player_id
    else
      players << self.white_player_id
    end
    return players.uniq
  end

  def opponent_name(player)
    if player == self.white_player_id
        User.find(self.white_player_id).email
    else
        User.find(self.black_player_id).email
    end    
  end

  def player_in_check?(color)
     game = self
     king = game.pieces.find_by(type: "King", color: color)
     return king.is_in_check?
  end

  def player_checkmate?(color)
    game = self
    king = game.pieces.find_by(type: "King", color: color)
    return king.is_in_checkmate?
  end

  def is_stalemate?(color)
    game = self
    king = game.pieces.find_by(type: "King", color: color)
    return king.is_in_stalemate?
  end

  def populate_game!
    color = ""

    [2,7].each do |y|
      (1..8).each do |x|
        y == 2? color = "white" : color ="black"
        Pawn.create(game_id: id, position_x: x, position_y: y, color: color, :image => Pawn.get_image(color))
      end
    end

    [1,8].each do |y|
      [1,8].each do |x|
        y == 1? color = "white" : color ="black"
        Rook.create(game_id: id, position_x: x, position_y: y, color: color, :image => Rook.get_image(color))
      end
    end

     [1,8].each do |y|
      [2,7].each do |x|
        y == 1? color = "white" : color ="black"
          Knight.create(game_id: id, position_x: x, position_y: y, color: color, :image => Knight.get_image(color))
        end
      end

      [1,8].each do |y|
      [3,6].each do |x|
        y == 1? color = "white" : color ="black"
        Bishop.create(game_id: id, position_x: x, position_y: y, color: color, :image => Bishop.get_image(color))
      end
    end

      [1,8].each do |y|
        y == 1? color = "white" : color ="black"
        Queen.create(game_id: id, position_x: 4, position_y: y, color: color, :image => Queen.get_image(color))
      end

      [1,8].each do |y|
        y == 1? color = "white" : color ="black"
        King.create(game_id: id, position_x: 5, position_y: y, color: color, :image => King.get_image(color))
      end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find_by_id(params[:id])
    @pieces = @game.pieces
  end

  def pending
    @game = Game.pending
    render action: :index
  end

  def playing
    @game = Game.playing
    render action: :index
  end

  def complete
    @game = Game.complete
    render action: :index
  end

  def new
    @game = Game.new
  end

  def create
    opponent_id = game_params[:black_player_id]
    @game = Game.create(:black_player_id => opponent_id, :white_player_id => current_user.id, :next_player_id => current_user.id)
    redirect_to game_path(@game)
  end

  def update
    @game = Game.find(params[:id])
    @game.update_attributes(:black_player_id => current_user.id)
    redirect_to game_path(@game)
  end

  def forfeit
    @game = Game.find(params[:id])
    @game.forfeit!(current_user)
    redirect_to root_path
  end

  def castle_king_side
    @game = Game.find(params[:id])
    if @game.next_player_id == @game.white_player_id
      color = "white"
    else
      color = "black"
    end
    king = @game.pieces.where(type: "King", color: color)[0]
    if king.can_castle
      king.castle!("kingside_castle", color)
      @game.next_player(@game.next_player_id)
      redirect_to game_path(@game)
    end
  end

  def castle_queen_side
    @game = Game.find(params[:id])
    if @game.next_player_id == @game.white_player_id
      color = "white"
    else
      color = "black"
    end
    king = @game.pieces.where(type: "King", color: color)[0]
    if king.can_castle
      king.castle!("queenside_castle", color)
      @game.next_player(@game.next_player_id)
      redirect_to game_path(@game)
    end
  end


  private

  def game_params
    params.require(:game).permit(:black_player_id, :result)
  end


end

app/helpers/games_helper.rb
module GamesHelper
  
 def check_piece(x, y)
    @pieces.each do |piece|
      if piece != nil        
        if piece.position_x == x && piece.position_y == y
          # return link_to image_tag(piece.image, :class=>"img-responsive", :id =>"draggable"), piece_path(piece, position_x: x, position_y: y), :method => :put, :id =>"draggable"
          if piece.color == "white"
            return image_tag(piece.image, :class=>"img-responsive white-piece")
          else
            return image_tag(piece.image, :class=>"img-responsive black-piece")
          end          
        end
      end
    end
    return  content_tag(:div, "", class: "square")

    
  end
end

app/views/games/index.html.erb
  <% @games.each do |game| %>
    <% if current_user && current_user.id == game.white_player_id || current_user && current_user.id == game.black_player_id %>
      <div class="game-box col-10 offset-1">
        <h1>Your player:  <%= link_to game.name(current_user.id), game_path(game) %></h1><br />
        <h2>Game status:  <%= game.result %></h2>
      </div>
    <% end %>
  <% end %>

app/views/games/new.html.erb
<div class="game-box col-10 offset-1">
  <h1>Start a New Game</h1>
  <p>You can start a new game by selecting another player who's registered on the Chesster server.</p>

  <%= simple_form_for @game, :url => games_path do |f| %>
    <%= f.input :black_player_id, :collection => User.all %>
    <br/>
    <%= f.submit "Start Game", :class => 'btn btn-primary' %>
  <% end %>  
</div>

app/views/games/show.html.erb
<br/>
<div id="action_box" class="col-10 offset-4 row" >
<h4> Next move: &nbsp; &nbsp;</h4>
  <% if @game.next_player_id == @game.white_player.id %>
   <h4> <%= "White Player" %> </h4>
  <% else %>
   <h4><%= "Black Player" %> </h4>
  <% end %>
</div>
<hr/>
<div id="game_board" data-current_player=<%= current_user.id %> data-move_player=<%= @game.next_player_id %> data-white_player=<%= @game.white_player.id %> class="col-10 offset-4">

  <table class="chessboard">

    <% (1..8).to_a.reverse.each do |row_number| %>
      <tr>
        <% ["A","B","C","D","E","F","G","H"].each_with_index do |rank , index| %>
          <% piece = @pieces.find {|piece| piece.position_y == row_number && piece.position_x == index+1} %>

          <% if row_number.odd? %>
            <% if index.even? %>
              <td class="black tile droppable draggable" data-position_x=<%= index+1 %> data-position_y=<%= row_number %> data-piece-id= <%= piece ? piece.id : nil %> data-type=<%= piece ? piece.type : nil %> data-en_passant=<%= piece ? piece.en_passant : nil %>>
                <%= check_piece(index + 1, row_number) %>
              </td>
            <% else %>
              <td class="white tile droppable draggable "  data-position_x=<%= index+1 %> data-position_y=<%= row_number %> data-piece-id= <%= piece ? piece.id : nil %> data-type=<%= piece ? piece.type : nil %> data-en_passant=<%= piece ? piece.en_passant : nil %>>
                <%= check_piece(index + 1, row_number) %>
              </td>
            <% end %>
          <% else %>
            <% if index.even? %>
              <td class="white tile droppable draggable" data-position_x=<%= index+1 %> data-position_y=<%= row_number %> data-piece-id= <%= piece ? piece.id : nil %> data-type=<%= piece ? piece.type : nil %> data-en_passant=<%= piece ? piece.en_passant : nil %>>
                <%= check_piece(index + 1, row_number) %>
              </td>
            <% else %>
              <td class="black tile droppable draggable" data-position_x=<%= index+1 %> data-position_y=<%= row_number %> data-piece-id= <%= piece ? piece.id : nil %> data-type=<%= piece ? piece.type : nil %> data-en_passant=<%= piece ? piece.en_passant : nil %>>
                <%= check_piece(index + 1, row_number) %>
              </td>
            <% end %>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>

</div>
<br class="clear"/>
<hr/>
<% if @game.result == nil %>
      <h4>Available actions: &nbsp; &nbsp; </h4>
  <div id="action_box_transp" class="col-10 offset-4 row">
      <%= link_to 'Forfeit', forfeit_game_path(@game), method: :post, style: "margin-left: 10px", class: 'btn btn-block btn-danger',data: {confirm: 'Are you sure?'} %>
    </div>
  </div>
<% end %>
<br/>
<div style="text-align: center" id="action_box" class="col-10 offset-4 row">
  <h4>King in Check: &nbsp; &nbsp;</h4>
  <% color = "white" %>
  <% if @game.next_player_id == @game.black_player.id %>
    <% color = "black" %>
    <% if @game.player_in_check?(color) %>
      <h4>Yes</h4>
    <% else %>
      <h4>No</h4>
    <% end %>
  <% end %>
</div>
 <br/>
<div id="action_box" class="col-10 offset-4 row">
  <h4>King in Checkmate: &nbsp; &nbsp;</h4>
  <% color = "white" %>
  <% if @game.next_player_id == @game.black_player.id %>
    <% color = "black" %>
    <% if @game.player_checkmate?(color) %>
      <h4>Yes</h4>
    <% else %>
      <h4>No</h4>
    <% end %>
  <% end %>
</div>
<br/>
<div id="action_box" class="col-10 offset-4 row">


  <h4>King in Stalemate: &nbsp; &nbsp;</h4>
  <% color = "white" %>
  <% if @game.next_player_id == @game.black_player.id %>
    <% color = "black" %>
    <% if @game.is_stalemate?(color) %>
      <h4>Yes</h4>
    <% else %>
      <h4>No</h4>
    <% end %>
  <% end %>
</div>
<br/>
<br/>
<br/>

<br class="clear"/>

 <div id="myModal" class="modal" method="post" style="text-align: center;">
  <div class="modal-content">
    
    
    <!-- <span class="close">CLOSE</span> -->
    <form id="myForm">
      <h3>Choose your promotion:</h3>
      <h5>If you don't make any choice your pawn will not promote and remain.. a pawn!</h5>
      <h5>Click anywhere out of the box to make another move instead</h5>
      <br/>
      <div class="row center" style="text-align: center";>
        
        <div class="promo">
          <% if @game.next_player_id == @game.white_player.id %>
            <%= image_tag('chess_piece_queen_white.png', :class=>"img-responsive white-piece")%><br/>
          <% else %>
            <%= image_tag('chess_piece_queen_black.png', :class=>"img-responsive white-piece")%><br/>
          <% end %>
          <input type="radio" id="promoChoice1" name="contact" value="Queen">
          <label for="promoChoice1">Queen </label> <br/> 
        </div>
       
         <div class="promo">
            <% if @game.next_player_id == @game.white_player.id %>
            <%= image_tag('chess_piece_rook_white.png', :class=>"img-responsive white-piece")%><br/>
          <% else %>
            <%= image_tag('chess_piece_rook_black.png', :class=>"img-responsive white-piece")%><br/>
          <% end %>
          <input type="radio" id="promoChoice1" name="contact" value="Rook">
          <label for="promoChoice1">Rook </label> <br/> 
        </div class="center">
      
         <div class="promo">
            <% if @game.next_player_id == @game.white_player.id %>
            <%= image_tag('chess_piece_bishop_white.png', :class=>"img-responsive white-piece")%><br/>
          <% else %>
            <%= image_tag('chess_piece_bishop_black.png', :class=>"img-responsive white-piece")%><br/>
          <% end %>
          <input type="radio" id="promoChoice1" name="contact" value="Bishop">
          <label for="promoChoice1">Bishop </label> <br/> 
        </div>
        
        <div class="promo">
          <% if @game.next_player_id == @game.white_player.id %>
            <%= image_tag('chess_piece_knight_white.png', :class=>"img-responsive white-piece")%><br/>
          <% else %>
            <%= image_tag('chess_piece_knight_black.png', :class=>"img-responsive white-piece")%><br/>
          <% end %>
          <input type="radio" id="promoChoice1" name="contact" value="Knight">
          <label for="promoChoice1">Knight </label> <br/> 
        </div>

      </div>
      <div>
        <button type="submit">PROMOTE!</button>
      </div>
    </form>
 </div>
</div>